---
- name: Testing andrewrothstein.yq
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'yq --verison'
      ansible.builtin.command: /usr/local/bin/yq --version
      changed_when: false
      register: yq_test_output
    - name: Output of 'yq --version'
      ansible.builtin.debug:
        msg: '{{ yq_test_output.stdout }}'
